### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\xf4' in position 34: illegal multibyte sequence

### ISSUE THREAD

**Issue by ImageOnly** [L4GSP1KE/Upload-Assistant#10]
https://p.teknik.io/Simple/ctIRN

**Comment by L4GSP1KE** [comment]
I was unable to reproduce, but it's maybe fixed now?

**Comment by ImageOnly** [comment]
Yes, pulled and it's fixed! Ty for always fixing so quickly!
