### ISSUE TITLE
add labels to identify torrent on clients(rtorrent)

### ISSUE THREAD

**Issue by BradleyRL** [L4GSP1KE/Upload-Assistant#103]
Is there any way to add a label to the torrent when adding it to the client?

**Comment by L4GSP1KE** [comment]
not at the moment. leaving this open for when i (or someone else) finds the time

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/b124a89832bffdf6ac369ac48718f2375bc82f3d
