### ISSUE TITLE
Enhancement Request - Argument/Configuration options for Categories or Tags in Qbit

### ISSUE THREAD

**Issue by Kha-kis** [L4GSP1KE/Upload-Assistant#111]
I am running into a use case where I am in need of additional functionality of Upload-Assistant.

I would like to specify categories to Qbit when performing upload.py.

Another option for my used would be to use tags (this leaves me with less functionality on the qbit side).

In order to change this at will, having the ability to issue an argument to make the change to categories or tags would be super awesome.

Another possible solution would be to be able to specify a path for a separate config file where i could set the the tags in the TORRENT_CLIENTS section in the config.py. 

Thanks for all of your great work on this tool!

**Comment by L4GSP1KE** [comment]
Is this the point where i tell you it already supports tags? Peep the example config for a usage example. Thanks :)

**Comment by Kha-kis** [comment]
Maybe I am not able to understand the config correctly.

In the config I see:
 "qbit_tag" : "tag"
 
This allows for a single tag. 
I would not want for every use of the script to use the same tag.

Please let me know if I am missing how this functions.

**Comment by L4GSP1KE** [comment]
added --qbit-tag, please confirm if it works

**Comment by Kha-kis** [comment]
I have tested this and was unable to get it to work.

python3 upload.py --qbit-tag test <path>
This throws a Traceback
```
Traceback (most recent call last):
  File "/home/Upload-Assistant/upload.py", line 486, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/Upload-Assistant/upload.py", line 91, in do_the_thing
    path = os.path.abspath(path)
  File "/usr/lib/python3.9/posixpath.py", line 374, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

python3 upload.py <path> --qbit-tag test
This performs normal functions however the tag is not added.

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/dd9b577bf070ffdce8f2a8e11b1d81a404dd58bf
I actually tested it this time so it should work

**Comment by Kha-kis** [comment]
Works like a dream! thanks!
