### ISSUE TITLE
[Request] PTP Trumpable tags

### ISSUE THREAD

**Issue by gaddarkerim** [L4GSP1KE/Upload-Assistant#124]
There are two options before uploading torrent No English Subtitles and Hardcoded Subtitles. These can be read from mediainfo if there isn't English subtitle track the script can  prompt first option if the file doesn't contain any subtitle track second tag should be prompted and ask to user for subtitle language in two letter language code. ISO 639-1

That tags cannot be edited after uploading a torrent.

**Comment by a-nunes** [comment]
It could be solved by adding a option to manually set if one of the trumpable tags is true.

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/243eba6789e5f5237f36c008f2545e3e37f61ea9

reopen if does not work, is missing functionality, or you have suggestions

**Comment by gaddarkerim** [comment]
> [243eba6](https://github.com/L4GSP1KE/Upload-Assistant/commit/243eba6789e5f5237f36c008f2545e3e37f61ea9)
> 
> reopen if does not work, is missing functionality, or you have suggestions

IT marks torent as Trumpable (as in my case the file has English hardcoded subtitle) however mediainfo is created before this step so the final upload has Trumpable tag (Hardcoded subtitle) but the subtitle is set to No Subtitles. Maybe in final step the script could prompt to enter two letter language code (it might includes all languages in upload form or limited to 4-5) then the final upload has nothing to edit. Thanks for yur work.
