### ISSUE TITLE
[Feature Request] Add inform_version=1 to MediaInfo

### ISSUE THREAD

**Issue by milkdawg** [L4GSP1KE/Upload-Assistant#13]
Would you consider adding ability to include version in mediainfo output?

Can be done with 

```
from pymediainfo import MediaInfo

Dict = {'inform_version':'1'}
media_info = MediaInfo.parse(filename="file.mkv", output="STRING", full=False, mediainfo_options=Dict)
print (media_info)
```

This param is only available on mediainfo verions >= 21.03.  
Pymediainfo validates params before passing so if the user is using a version that doesn't support it, it still functions.

If the user is using a version old enough( at leaast 19.04) they will recieve this warning 
"/home7/.../python3.8/site-packages/pymediainfo/__init__.py:448: RuntimeWarning: This version of MediaInfo (v19.04) does not support resetting all options to their default values, passing it custom options is not recommended and may result in unpredictable behavior, see MediaInfoLib/issues/1128
  warnings.warn("

Could always add this as a param if above is not ok.

If you would like me to just make a PR let me know, figured it would be quicker for you to make this small change than review a PR.

**Comment by L4GSP1KE** [comment]
Implemented. I've been meaning to add this for a while as it's a great way to enforce 21.03 so we can get proper hdr/dv detection
