### ISSUE TITLE
Daily TV show episode support

### ISSUE THREAD

**Issue by d3mystified** [L4GSP1KE/Upload-Assistant#138]
Daily shows need to add title like:

```
Show 2022-12-29 1080p HDTV DD 5.1 x264
```

As an example, this file `Jeopardy.2022.03.04.720p.HDTV.x264.AC3.mkv` seems to be parsed as:

```
               'category': 'TV',
               'type': 'HDTV',
               'manual_source': None,
               'resolution': '720p',
               'tmdb_manual': '2912',
               'imdb': None,
               'mal': None,
               'tag': '',
               'service': '',
               'distributor': '',
               'manual_edition': '',
               'season': 'S01',
               'episode': 'E03',
```

And the generated name is `Name: Jeopardy! 1984 S01E03 720p HDTV DD 5.1 x264`.

The season and episode are incorrect of course.  Would be nice to be able to manually override this.

**Comment by mesol86** [comment]
I'm interested in this as well. How do solve it? I do not understand on "use a path that doesn't include extra directories".
