### ISSUE TITLE
Flag parsing broken? Path "does not exist"

### ISSUE THREAD

**Issue by d3mystified** [L4GSP1KE/Upload-Assistant#139]
On the latest image

```
ghcr.io/l4gsp1ke/upload-assistant    master    e8dd6495267f
```

I run this command (which I ran successfully yesterday):

```
docker run --rm -it     -v Upload-Assistant/config.py:/Upload-Assistant/data/config.py     -v /qbittorrent/:/downloads     ghcr.io/l4gsp1ke/upload-assistant:master       "/downloads/file.mkv"       -other -normal -params --tmdb $ID       -s 3 -debug
```

No matter what path I try I get this error:

```
Path: /downloads/file.mkv -other -normal -params does not exist
```

The file definitely exists, permissions are alright. 

When I run it without any other flags:

```
docker run --rm -it     -v Upload-Assistant/config.py:/Upload-Assistant/data/config.py     -v /qbittorrent/:/downloads     ghcr.io/l4gsp1ke/upload-assistant:master       "/downloads/file.mkv"       -debug
```

It works fine.

**Comment by TMD20** [comment]
```
        args, before_args = parser.parse_known_args(input)
        args = vars(args)
        # console.print(args)
        if len(before_args) >= 1:
            for each in before_args:
                args['path'].append(each)
                if os.path.exists(''.join(args['path'])):
                    break
```

The issue is the args your passing
Basically it assuming that your arguments are a path with spaces

**Comment by L4GSP1KE** [comment]
please let me know if https://github.com/L4GSP1KE/Upload-Assistant/commit/c02925dd99d1a89e7ac0b831bee95e93ec95b73e works better

**Comment by L4GSP1KE** [comment]
@d3mystified I'm curious as to the args you're providing as any valid args will not be saved seperately (and added to path). But have an attempt #2 https://github.com/L4GSP1KE/Upload-Assistant/commit/b901c27e20f38ebb02245e0d90be715d7c6f0c82

**Comment by L4GSP1KE** [comment]
-other -normal -params are placeholders for any parameters you would pass the script, such as --imdb / --tmdb / etc and they should not be used in normal usage
