### ISSUE TITLE
new tracker

### ISSUE THREAD

**Issue by FuNFooKaS** [L4GSP1KE/Upload-Assistant#15]
can we get a new tracker addded?

**Comment by L4GSP1KE** [comment]
yes?

**Comment by FuNFooKaS** [comment]
Ok sweet how can i get ahold of you?

**Comment by FuNFooKaS** [comment]
i started tp convert one to my tracker but am running into problems

**Comment by L4GSP1KE** [comment]
You can find me on most of the sites I support. And saying that you're running into problems isn't at all helpful for getting the problems resolved

**Comment by FuNFooKaS** [comment]
All sorted now,thank you
