### ISSUE TITLE
Torrents being added to torrent client, missing the root folder

### ISSUE THREAD

**Issue by simbab0i** [L4GSP1KE/Upload-Assistant#16]
Hey,

I was trying the tool, and it worked perfectly but I had a problem when it adds the generated torrent file to the client (qBittorrent).

Let's say my structure is:
```
files/
├─ My.Torrent.File.Root.Folder.1080p.WEB-DL.BlaBla/
│  ├─ TheActualFile.1080p.WEB-DL.BlaBla.mkv
```
And I run the command like:
```
python upload.py /somewhere/files/My.Torrent.File.Root.Folder.1080p.WEB-DL.BlaBla/ --args
```

Expected behavior:

- The generated `.torrent` file covers the root folder (`My.Torrent.File.Root.Folder.1080p.WEB-DL.BlaBla`) and obviously the file inside it.
- So when it's added to the torrent client, to the `local_path` in `data/config.py`, it would be `/local_path/My.Torrent.File.Root.Folder.1080p.WEB-DL.BlaBla/`, so that it finds the file `TheActualFile.1080p.WEB-DL.BlaBla.mkv` it's looking for.

What happens instead:

- The generated `.torrent` file only covers the file inside the root folder (`My.Torrent.File.Root.Folder.1080p.WEB-DL.BlaBla`) which is (`TheActualFile.1080p.WEB-DL.BlaBla.mkv`)
- And the same time, when adding to the torrent client, it only adds the `/local_path/` and not `/local_path/My.Torrent.File.Root.Folder.1080p.WEB-DL.BlaBla/` so that it would then find the file `TheActualFile.1080p.WEB-DL.BlaBla.mkv`. So I need to change the path everytime to include the file.

Possible solution:
Get the generated folder to cover the `path` in the initial command ran at first. So, when it adds the torrent file to the client with the `local_path`, it would be able to find the folder and the files inside it.

And it would be better if there was an option (possible auto-detection in the future) to either contain the root folder or not, assuming I might have
```
files/
├─ TheActualFile.1080p.WEB-DL.BlaBla.mkv
```
with no root folder, so it would need to only cover the file, and not the `./files/` also.

This isn't as hard as the issue's length makes it look like, I just wanted to give you a *very detailed* overview of the thing so you know what's happening exactly and probably help you save time debugging it 👍 

Also, thanks for the great repository, I really liked it, saved me tons of time generating MediaInfo and screenshots. I would also like to ask if you're planning to add a documentation for implementing new trackers (also those who possibly don't have APIs), so that I could try and add some myself.

Thank you again for your efforts and time.

**Comment by L4GSP1KE** [comment]
Thanks for the detailed report. The script doesn't hash folders into the .torrent if a single video file exists (this is intended behavior), and was adding it into the wrong directory, but should now be working as expected. I have plans to clean up the code and document it better eventually™ as well as add in new trackers. Until then, feel free to send me a dm if you want help or anything else.
