### ISSUE TITLE
Lensdump Screenshots - Feature

### ISSUE THREAD

**Issue by edge20200** [L4GSP1KE/Upload-Assistant#165]
Wondering about adding lensdump.com as a image hosting for screenshots.

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/pull/166

**Comment by edge20200** [comment]
Testing this and running into issue with it not uploading, i believe its not passing the api key in the header not sure where to put this to try and fix the issue. If a new issue needs to be opened let me know


X-API-Key: chv_asd_somekeyhere
