### ISSUE TITLE
Lensdump Failing to upload

### ISSUE THREAD

**Issue by edge20200** [L4GSP1KE/Upload-Assistant#168]
Testing this and running into issue with it not uploading, i believe its not passing the api key in the header not sure where to put this to try and fix the issue. If a new issue needs to be opened let me know

X-API-Key: chv_asd_somekeyhere

**Comment by sirius-sama** [comment]
This is because you didn't update your config.py. We updated the config file (example-config.py), please update your config.py as well. 
You'll see the option there for putting your Lensdump API.

**Comment by edge20200** [comment]
I updated everything with a git pull and redid my config file by copying the example-config.py and and editing the values with the correct keys including a brand new lensdump api key to be sure it was 100% correct.

**Comment by L4GSP1KE** [comment]
modified so lensdump uses the x-api-key header

**Comment by sirius-sama** [comment]
Sorry, it was my fault. I made a mistake with the API URL and didn't add base64 to the image naming.
Fixed now. #169

**Comment by edge20200** [comment]
Thanks for this fix!

**Comment by edge20200** [comment]
Any idea why editing a upload on a united based site the images then no longer show with the original img codes, is this a issue with lensdump or the code its creating?

**Comment by sirius-sama** [comment]
I never uploaded on united based site before with this script. But I tried after reading your comment, I edited the description (I think that's what you meant by "editing an upload"), made some changes, images still working. Working fine on my side. 
Still, there could be issues. Let's see what L4G says.

**Comment by edge20200** [comment]
So fixed my issue by having it use the img_url and removing the width as it fixed the issues i was having on United bases sites as well as TL

**Comment by L4GSP1KE** [comment]
temporarily reverted img bbcode for sites until they get the newer torrent editing page
