### ISSUE TITLE
Screenshot AR is now incorrect

### ISSUE THREAD

**Issue by MiM-MiM** [L4GSP1KE/Upload-Assistant#174]
https://github.com/L4GSP1KE/Upload-Assistant/commit/5d5fa2d3bd3e12c806037a5aff6751cf24c3be63

This commit needs reverted, it the "PAR" as ffmpeg calls it is not exactly 1, then it has to be scaled.  You can verify this on any player that obeys the relevant video codec spec.
If the DAR is not exactly the same as the SAR, then it is anamorphic and must be scaled.  If the video should actually be done in the AR this commit aims to fix, you need to fix the raw stream and not just apply some hacky fix that doesn't actually fix anything other than make screens no longer represent how it is displayed.

**Comment by L4GSP1KE** [comment]
thanks for calling out my stupid
