### ISSUE TITLE
What output should I expect?

### ISSUE THREAD

**Issue by kevin201** [L4GSP1KE/Upload-Assistant#175]
Is there a slightly more detailed walk through anywhere? I'm running the docker image but not getting any output at all, just "Queuing these files" then three blank lines. It would be helpful to have a minimal working config.py with some indication of what to expect as output.

**Comment by L4GSP1KE** [comment]
The example config that exists is as close to a minimal working config without leaking credentials or accounting for setup differences. However you would have already seen an error of some sort if your config had any major issues. Any config issues such as improper credentials/etc will probably result in a warning when the script decides to use them. Without knowing the command you used, I'd guess that it might have been an issue with how you provided the path. Here's an example command:

```
docker run --rm -it --network=host \
-v /full/path/to/config.py:/Upload-Assistant/data/config.py \
-v /full/path/to/downloads:/downloads \
ghcr.io/l4gsp1ke/upload-assistant:master /downloads/path/to/content/relative/to/the/downloads/folder
```

**Comment by kevin201** [comment]
Appreciate the reply, thank you.

I'm sure once I get my head around this it will seem very obvious. I'm trying to get manual output to see what would be produced. It's the two folder references I'm having trouble with. What should go in them? The "content" folder should be a relative, not absolute address?

If I could get it to output something, I'd have a starting point. I've tried using -m for manual and --debug for extra verbosity, but still see only the "Queuing" message, then nothing.

````
~$ docker run --rm -it -v /home/kevin/Documents/Upload-Assistant/config.py:/Upload-Assistant/data/config.py -v /home/kevin/Documents/downloads:/downloads ghcr.io/l4gsp1ke/upload-assistant:master /home/kevin/Documents/TV -m --debug 

Queuing these files:



~$
````

**Comment by L4GSP1KE** [comment]
All that the docker container does is call the upload script as if you were running it on bare metal except that you would need to go through the extra steps of allowing it to see the config, as well as the files you wish to upload (generally a client's downloads folder). That is what these two bind mounts are. 

`-v /full/path/to/config.py:/Upload-Assistant/data/config.py` makes it so that /full/path/to/config.py on your host machine is the same as /Upload-Assistant/data/config.py in the container, which is where the config is expected to be.

`-v /full/path/to/downloads:/downloads` makes it so that /full/path/to/downloads/ on your host machine is mapped to /downloads/ inside of the container.



So for example. If I wished to upload a file located at `/full/path/to/downloads/Movie.mkv` on my host machine, the command I would use is: 

```
docker run --rm -it --network=host \
-v /full/path/to/config.py:/Upload-Assistant/data/config.py \
-v /full/path/to/downloads:/downloads \
ghcr.io/l4gsp1ke/upload-assistant:master /downloads/Movie.mkv```

**Comment by kevin201** [comment]
Many thanks. This has given me the information I needed to get started. I can take it from here:

```
~$ docker run --rm -it -v /home/kevin/Documents/Upload-Assistant/config.py:/Upload-Assistant/data/config.py -v /home/kevin/Documents/TV:/downloads ghcr.io/l4gsp1ke/upload-assistant:master /downloads -m --debug 
Gathering info for downloads
ID: downloads
Exporting MediaInfo...
MediaInfo Exported.
Saving Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 0:00:00
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 485, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Upload-Assistant/upload.py", line 151, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli') 
  File "/Upload-Assistant/src/prep.py", line 317, in gather_prep
    meta = await self.get_tmdb_id(filename, meta['search_year'], meta, meta['category'], untouched_filename)
  File "/Upload-Assistant/src/prep.py", line 1080, in get_tmdb_id
    search.tv(query=filename, first_air_date_year=search_year)
  File "/usr/lib/python3.10/site-packages/tmdbsimple/search.py", line 182, in tv
    response = self._GET(path, kwargs)
  File "/usr/lib/python3.10/site-packages/tmdbsimple/base.py", line 110, in _GET
    return self._request('GET', path, params=params)
  File "/usr/lib/python3.10/site-packages/tmdbsimple/base.py", line 105, in _request
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/search/tv?query=You&first_air_date_year=&api_key=tmdb_api+key
```

Thanks again. Looking forward to experimenting with this!

**Comment by MLSci** [comment]
> -v /full/path/to/downloads:/downloads

and

> /downloads/Movie.mkv

This is confusing naming convention. People wouldn't expect only the 2nd and 3rd `downloads` refer to the same thing. Either change the first line to -
`-v /full/path/to/the/directory/containing/mkv:/downloads`
Or modify the logic then remove the `/downloads` part in the second line, which is a repeat and not necessary.
