### ISSUE TITLE
Remuxes aren't tagged as remux when uploading to Anthelion

### ISSUE THREAD

**Issue by Slikkster** [L4GSP1KE/Upload-Assistant#192]
Always have to go edit the torrent after uploading and tick the Remux box. Anthelion's API supports this flag, so it seems like Upload Assistant should be setting it when uploading?

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/5e0d8d3ae98ec8f215bea358daaba1ad8e81a64a
