### ISSUE TITLE
Torrent path mapping - possible bug

### ISSUE THREAD

**Issue by shapelessvoid** [L4GSP1KE/Upload-Assistant#196]
Hi folks,

Looking at this snippet: https://github.com/L4GSP1KE/Upload-Assistant/blob/a014a17021477ec0f6d082cee4f9682c408bea2e/src/clients.py#L205

Aren't `local_path` and `remote_path` flipped in the replace function?

My understanding is that `remote_path` is where qbit sees the files and `local_path` is where the uploader sees them. So to make things equal for the uploader to do a comparison later on, it should replace `remote_path` prefix with the `local_path` prefix.

**Comment by L4GSP1KE** [comment]
You're probably correct. There's no reason for the session folder path to be mapped, so I will likely remove this code sometime soon. Thanks!
