### ISSUE TITLE
qBittorrent + create subfolder to support fast resume (no rehashing)

### ISSUE THREAD

**Issue by shapelessvoid** [L4GSP1KE/Upload-Assistant#197]
The tool works fine for tv seasons with more than one file, since they are in their own folder. If the option in qbit to create subfolder for all torrents (even single file torrents) is checked though the usage of already existing torrent is not possible and rehashing is initiated.

What seems to happen is when qbit's `BT_backup` folder is traversed and the correct `.torrent` is located there is a path check which fails. More specifically this one: 
https://github.com/L4GSP1KE/Upload-Assistant/blob/a014a17021477ec0f6d082cee4f9682c408bea2e/src/clients.py#L136

Here `str(torrent.files[0])` evaluates to something like `Ubuntu-22.04/Ubuntu-22.04.mkv` (due to qbit creating subfolder for individual file torrents), on the other hand `os.path.basename(torrent.files[0])` evaluates to `Ubuntu-22.04.mkv`. This failed check fails the fast resume flow and rehashing is in order.

Could that case be handled in a non-hacky way?

**Comment by shapelessvoid** [comment]
Here is a quick and dirty fix which will enable no rehashing and resume of torrents with qBit Subfolder strategy enabled (for anyone that has an urge to play with that):

**WARNING!** Use at your own risk.

```diff
diff --git i/src/clients.py w/src/clients.py
index 20365e5..610df0a 100644
--- i/src/clients.py
+++ w/src/clients.py
@@ -133,7 +133,11 @@ class Clients():
             # If one file, check for folder
             if len(torrent.files) == len(meta['filelist']) == 1:
                 if os.path.basename(torrent.files[0]) == os.path.basename(meta['filelist'][0]):
-                    if str(torrent.files[0]) == os.path.basename(torrent.files[0]):
+                    torrent_file_path = str(torrent.files[0])
+                    torrent_filename = os.path.basename(torrent.files[0])
+                    torrent_qbit_folder = os.path.splitext(torrent_filename)[0]
+                    torrent_path_with_folder = torrent_qbit_folder + os.sep + torrent_filename
+                    if torrent_file_path == torrent_filename or torrent_file_path == torrent_path_with_folder:
                         valid = True
                 else:
                     wrong_file = True
@@ -307,7 +311,7 @@ class Clients():
             if os.path.normpath(am_config).lower() in os.path.normpath(path).lower() and am_config.strip() != "":
                 auto_management = True
         qbt_category = client.get("qbit_cat") if not meta.get("qbit_cat") else meta.get('qbit_cat')
-        qbt_client.torrents_add(torrent_files=torrent.dump(), save_path=path, use_auto_torrent_management=auto_management, is_skip_checking=True, content_layout='Original', category=qbt_category)
+        qbt_client.torrents_add(torrent_files=torrent.dump(), use_auto_torrent_management=True, is_skip_checking=True, content_layout='Subfolder', category=qbt_category)
         # Wait for up to 30 seconds for qbit to actually return the download
         # there's an async race conditiion within qbt that it will return ok before the torrent is actually added
         for _ in range(0, 30):
```

**Comment by L4GSP1KE** [comment]
> What seems to happen is when qbit's `BT_backup` folder is traversed and the correct `.torrent` is located there is a path check which fails. More specifically this one:
> 
> https://github.com/L4GSP1KE/Upload-Assistant/blob/a014a17021477ec0f6d082cee4f9682c408bea2e/src/clients.py#L136
> 
> Here `str(torrent.files[0])` evaluates to something like `Ubuntu-22.04/Ubuntu-22.04.mkv` (due to qbit creating subfolder for individual file torrents), on the other hand `os.path.basename(torrent.files[0])` evaluates to `Ubuntu-22.04.mkv`. This failed check fails the fast resume flow and rehashing is in order.


This is intended functionality to filter out .torrents that were originally hashed with an included folder and remove the folder if needed (which is impossible without rehashing). Do note that using the "Create Subfolder" option when adding a to qBittorrent does not actually edit the .torrent in your session folder and anything that this script considers "valid" will be valid regardless of what this option is set to.

**Comment by shapelessvoid** [comment]
@L4GSP1KE on that thrain of thought, could we at least have the qbit client properties for setting (forcing) `use_auto_torrent_management` and `content_layout` set in the config? Also, need to not set (ignore) the `save_path` to force qbit use the category I've provided (I think). Could these be set in the config?

**Comment by L4GSP1KE** [comment]
@shapelessvoid https://github.com/L4GSP1KE/Upload-Assistant/blob/master/data/example-config.py#L185-L191
