### ISSUE TITLE
Will not auto seed

### ISSUE THREAD

**Issue by FuNFooKaS** [L4GSP1KE/Upload-Assistant#20]
I updated this morning and since then it seems it will not auto seed the torrent  to my site STC. it says it did

Adding to rtorrent
Creating fast resume
Adding and starting torrent

**Comment by L4GSP1KE** [comment]
none of the rutorrent code has changed and still works on my test clients. I suggest you double check your configuration

**Comment by FuNFooKaS** [comment]
i did not alter any files when i updated   i reverted back to my original upload.py ans tracker config file still no auto seed,the file to make itauto seed would be config.py?

**Comment by FuNFooKaS** [comment]
Hmm  i revered back to my old configuration i backup before the update and it will still not auto seed.......any ideas as to why?Where to look?
