### ISSUE TITLE
Missing title tag and note for DV HDR WEBDL on BLU

### ISSUE THREAD

**Issue by Slikkster** [L4GSP1KE/Upload-Assistant#205]
For WEBDLs with DV HDR or DV HDR10+, BLU requires the title to include "Hybrid" (I think, not super clear on this) after the year/season (and cut/ratio if those are included), and also the note "This release contains a derived Dolby Vision profile 8 layer. Comparisons not required as DV and HDR are from same provider." in code tags at the beginning of the description.

Would it be possible to have Upload Assistant add these automatically?

Examples of the mediainfo where they should be added:
DV HDR file: Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
DV HDR10+ file: Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible

There are probably more HDR scenarios where this is required... I am not clear on the specifics. BLU has a wiki page about the naming and another about HDR if needed; let me know if I should link here.

**Comment by L4GSP1KE** [comment]
Added `--webdv` which will prompt and generate the appropriate note in the description. This can't be done fully automatically.

**Comment by Slikkster** [comment]
Disappointing it can't be automated, but thank you for adding the cli parameter for it.
