### ISSUE TITLE
Upload via discord

### ISSUE THREAD

**Issue by FuNFooKaS** [L4GSP1KE/Upload-Assistant#21]
so i get it all ready to upload but i  any of the reactions i click on do not upload the torrent.see the picture

https://i.gyazo.com/e16a65268a76c44a8f6cec89ef665794.png

**Comment by L4GSP1KE** [comment]
select the reactions for the tracker(s) you want to upload to, and then press the green check to upload

**Comment by FuNFooKaS** [comment]
i assume i must be doing something wrong then as i have no trackers to react to

**Comment by L4GSP1KE** [comment]
i assume that plane reaction?
