### ISSUE TITLE
HDT Wrong Link to Screenshot

### ISSUE THREAD

**Issue by mesol86** [L4GSP1KE/Upload-Assistant#210]
Uploaded format of screenshot become like this:
`
[url=https://images2.imgbox.com/ba/8a/mJag3Csq_o.png][imgw]https://thumbs2.imgbox.com/ba/8a/mJag3Csq_t.png[/imgw][/url]
[url=https://images2.imgbox.com/d9/d0/lpOcI1s3_o.png][imgw]https://thumbs2.imgbox.com/d9/d0/lpOcI1s3_t.png[/imgw][/url]
[url=https://images2.imgbox.com/d6/ef/bD5mxLi5_o.png][imgw]https://thumbs2.imgbox.com/d6/ef/bD5mxLi5_t.png[/url]
`

It should be like this:
`
[url=https://images2.imgbox.com/ba/8a/mJag3Csq_o.png][img]https://thumbs2.imgbox.com/ba/8a/mJag3Csq_t.png[/imgw][/url]
[url=https://images2.imgbox.com/d9/d0/lpOcI1s3_o.png][img]https://thumbs2.imgbox.com/d9/d0/lpOcI1s3_t.png[/imgw][/url]
[url=https://images2.imgbox.com/d6/ef/bD5mxLi5_o.png][img]https://thumbs2.imgbox.com/d6/ef/bD5mxLi5_t.png[/url]
`

**Comment by sirius-sama** [comment]
I thought **imgw** would be right one, because when I pressed **img** bbcode button on the site, it generated **imgw** tag.
But now I see **img** is better. Anyways, fixed now. #211 f26384daca1d377343e1c9ebed43233c2482a376
