### ISSUE TITLE
MTV Error

### ISSUE THREAD

**Issue by edge20200** [L4GSP1KE/Upload-Assistant#212]
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 564, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Upload-Assistant/upload.py", line 287, in do_the_thing
    if check_banned_group(tracker_class.tracker, tracker_class.banned_groups, meta):
AttributeError: 'MTV' object has no attribute 'banned_groups'

**Comment by mesol86** [comment]
These are the banned group for MTV
`
3LTON, [Oj], ZKBL, ViSiON, FUM, LOAD, ELiTE, ZmN, h65, mRS, PandaRG, DeadFish, JIVE, XS, TM, BDP, RARBG, ION10, EVO (except WEB-DLs), QxR, anything related with IPT network, mSD, x0r
`

Tried to upload FLUX, gotten the same error.

**Comment by L4GSP1KE** [comment]
this is a known issue, but it turns out MTV support still needs a good chunk of work so i'll be leaving it broken for now

**Comment by sirius-sama** [comment]
Fixed here. #213

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/0f1162457d072a67c4da67885e0a4564b701c2c5
