### ISSUE TITLE
Hawke.uno NOGRP Tag

### ISSUE THREAD

**Issue by jonandeva** [L4GSP1KE/Upload-Assistant#221]
Hi. When uploading a file with the tag -NOGRP to Hawke.uno, the upload assistant removes the tag. A mod commented, "Please add a - NoGRP or similar if none is in the filename." Sounds like even if there's no tag they want a NOGRP tag, same if the tag is actually NOGRP.

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/335b3a2da1cd6109adb3f3c53840c53daf2820b0
