### ISSUE TITLE
Support Fappaizuri

### ISSUE THREAD

**Issue by fappaizuri** [L4GSP1KE/Upload-Assistant#222]
Can the TorrentTrader tracker source be supported? We do not have an API for uploading yet.

**Comment by swannie-eire** [comment]
whats the link to the site you want to support?

**Comment by djlive1** [comment]
https://fappaizuri.me

**Comment by swannie-eire** [comment]
Great thanks was not sure if site was called torrent trader or Fappaizuri

Does this site have an upload API or search API?

**Comment by fappaizuri** [comment]
No we do not have API or API search, can it be done without API?

**Comment by swannie-eire** [comment]
> No we do not have API or API search, can it be done without API?
> 
> PS: Still hard to add API to make it work I guess

Yes it can be done without Api for upload and search but it makes it a lot more difficult. 

Never heard of this tracker. I assume it allows movies and tv as that is all that UA is capable of uploading

**Comment by fappaizuri** [comment]
We are a JAV/Hentai tracker

**Comment by fappaizuri** [comment]
Oh, understand. JAV database api wont be enough for it?

**Comment by swannie-eire** [comment]
> Oh, understand. JAV database api wont be enough for it?

What JAV db. Is it reliable and does it have an api

**Comment by L4GSP1KE** [comment]
No interest in supporting adult sites. A separate tool would likely be better suited for the task anyways.
