### ISSUE TITLE
HDT errror with cookies

### ISSUE THREAD

**Issue by swannie-eire** [L4GSP1KE/Upload-Assistant#223]
@sirius-sama

It looks like the code is trying to access the cookies without checking if they are there first.

  File "/Upload-Assistant/src/trackers/HDT.py", line 190, in upload
    with open(cookiefile, 'rb') as cf:
FileNotFoundError: [Errno 2] No such file or directory: '/Upload-Assistant/data/cookies/HDT.pkl'

You have a function validate credentials but it is never called so it not validated that the cookies file exist

**Comment by swannie-eire** [comment]
disregard i can see that function is called from upload.py

**Comment by sirius-sama** [comment]
Hey, is it working all good now?

**Comment by swannie-eire** [comment]
> Hey, is it working all good now?

Yeah I use the modules from L4G with my script and i dont call validate_creds function hence why i was getting the error. 

A question for you is there a reason why you download the torrent from HDT instead of just modding the existing torrent? 

I have been uploading to HDT for years but i just mod the torrent i uploaded instead of downloading the one from the site.
All you need is to add a function that mods the torrent tracker like below. Saves a load of work of having to download the torrent when you know all that really needs to be done is add your announce with passkey to it.
await torrent.add_tracker_torrent(meta, tracker, source_flag, my_announce_url, comment)

`
                            await torrent.add_tracker_torrent(meta, self.tracker, self.source_flag,
                                                             self.config['TRACKERS']['HDT'].get('my_announce_url'),
                                                             "https://hd-torrents.org/details.php?id=" + meta[
                                                                 'torrenthash'])`


Also your module has the wrong source flag it should be 'hd-torrents.org' not HDT. You wont need to download the HDT torrent if you have the correct source flag and just add the user announce+passkey

**Comment by swannie-eire** [comment]
> > A question for you is there a reason why you download the torrent from HDT instead of just modding the existing torrent?
> 
> I didn't know modding would be a great option.
> 
> > I have been uploading to HDT for years but i just mod the torrent i uploaded instead of downloading the one from the site.
> 
> WOAH! This is really impressive. Thanks for the idea. I will modify it soon. Actually, I don't upload much there. I decided to make a script for HDT, so I added the support in this script.
> 
> > Also your module has the wrong source flag it should be 'hd-torrents.org' not HDT.
> 
> I will change this too.
> 
> Thanks a lot.

I put in a pull request for it earlier.

Have a look and a test and see what you think.

**Comment by swannie-eire** [comment]
> It's throwing an [error](https://pastebin.com/raw/gsiW80M3) on torrenthash. Because the value of `meta['torrenthash']` is `None` I checked my other uploads tmp files, all have a torrenthash None value
> 
> I thought of fixes for this:
> 
>     1. Grab the hash from the successful upload page using regex.
> 
>     2. Get hash from the "[HDT] Release Name.torrent" file. (This option sounds good)
> 
> 
> Btw, in the config file use "pid" instead of "my_announce_url" "my_announce_url" looks good though.
> 
> ```
> "pid" : "your_pid_here"
> # Note: Copy your PID from the site: My Panel > Change PID
> ```
> 
> Let me know your thoughts. Thanks.

Weird. It worked perfect with me on the latest version..


I'll have a look later and update with a comment

**Comment by sirius-sama** [comment]
I just looked into a hdt metafile, and there was no use of ```https://hd-torrents.org/details.php?id=torrenthash```
Torrent hash is already available in the file which we're pushing to the site. We just have to change the announce URL with our personal announce URL.

**Comment by swannie-eire** [comment]
> 

I use that function for other trackers that L4G does not currently support so it does do things that are not needed in this case. I just dont want a function for each tracker so use that add_tracker_function to cover all and id prefer to keep all torrent editing in the common module. Feel free to edit that function or add a function to HDT to cover it.

The HDT description you have needs to be updated as I got a message from staff after uploading to HDT using your description. I just updated it with what i use so i need to look at what exactly you post vs what i do.

**Comment by sirius-sama** [comment]
Okay. I will update the script then. Btw what staff said? Is anything wrong with the description? I got that description from their forum. I didn't add extra stuff in there, just removed the screens part I guess :confused:

**Comment by swannie-eire** [comment]
> Okay. I will update the script then. Btw what staff said? Is anything wrong with the description? I got that description from their forum. I didn't add extra stuff in there, just removed the screens part I guess 😕

the thumbnails are too big. You may not of gotten the message from staff as you may use imgbox or another hosting site but i did as i use another image site.

**Comment by sirius-sama** [comment]
Hey, I updated my config.py yesterday when testing.
Can you tell me if you have "torrenthash" in meta file? I have None values.

**Comment by sirius-sama** [comment]
> the thumbnails are too big. You may not of gotten the message from staff as you may use imgbox or another hosting site but i did as i use another image site.

I am used imgbb. What tags do you use for images? (img, imgw)? 
How do you resize them on-site?

**Comment by swannie-eire** [comment]
> Hey, I updated my config.py with "my_announce_url" yesterday for testing. Can you tell me if you have "torrenthash" in meta file? I have None values. My error is coming because of the torrenthash's None value.

Yesh I have torrent hash in meta

`cat tmp/Of.an.Age.2022.720p.MA.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv/meta.json | grep hash                                                                            "torrenthash": "3cf12dbc18827e6162d5ceaa04a62ceae0922159",                                        "nohash": false,
    "rehash": false,`

Are you reusing an existing torrent or creating a new one. I don't create new ones so didn't test with that but will do it now.

**Comment by sirius-sama** [comment]
I tried both rehash and reuse. Still no torrenthash in the meta file. This is the reason I am getting the error.

**Comment by sirius-sama** [comment]
Also, your meta.json torrenthash and sites metafile hash doesn't match: a749aa12864ffcdbfd29d1449e1c4d75355aXXXX
I assume that's BASE.torrent hash in your meta.json. But if you use 2 diff hashes, then it wouldn't get seeded on the client.
Sorry if I am making this complex. :(

**Comment by swannie-eire** [comment]
> Also, your meta.json torrenthash and sites metafile hash doesn't match: a749aa12864ffcdbfd29d1449e1c4d75355aXXXX I assume that's BASE.torrent hash in your meta.json. But if you use 2 diff hashes, then it wouldn't get seeded on the client. Sorry if I am making this complex. :(

Hey,

I tested and can only replicate with new torrent. Try deleting tmp/FILE and then retrying with passing hash.

I will have a look at the cause and fix it.

**Comment by swannie-eire** [comment]
have a look there now it should work as expected. search var is the info hash and i am passing that now instead of using has from meta.

"https://hd-torrents.org/details.php?id=" + id is only adding a comment with the link to the torrent as i like this for all torrents as it makes them easy to find and mod. You can remove that argument from the function and the call you wont get that error.

**Comment by sirius-sama** [comment]
> have a look there now it should work as expected. search var is the info hash and i am passing that now instead of using hash from meta.
> 
> "https://hd-torrents.org/details.php?id=" + id is only adding a comment with the link to the torrent as i like this for all torrents as it makes them easy to find and mod. You can remove that argument from the function and the call so you wont get that error also

Now this works ^ :D
Thanks.

Comment out the downloading function, and let it stay there. We'll remove it later. Also please check the image problem. 
I saw your thumbnail image and mine, both have the same resolution and ratio, but your one looks smaller on the site. Which tag you're using?

Thanks again for the edit.

**Comment by swannie-eire** [comment]
> Comment out the downloading function, and let it stay there. We'll remove it later. 

This is done now.


> Also please check the image problem. I saw your thumbnail image and mine, both have the same resolution and ratio, but your one looks smaller on the site. Which tag you're using?
> 
> Thanks again for the edit.
Im surprised you did not get comments from the admins that yours are not small enough thumbnails.

Im not using a BB code tag im using another method as HDT dont support many options. Ill update the description in august when i have time.

**Comment by sirius-sama** [comment]
> > Comment out the downloading function, and let it stay there. We'll remove it later.
> 
> This is done now.

Thanks for your time.

> > Also please check the image problem. I saw your thumbnail image and mine, both have the same resolution and ratio, but your one looks smaller on the site. Which tag you're using?
> > Thanks again for the edit.
> > Im surprised you did not get comments from the admins that yours are not small enough thumbnails.
> 
> Im not using a BB code tag im using another method as HDT dont support many options. Ill update the description in august when i have time.


Okay.

**Comment by sirius-sama** [comment]
@swannie-eire bro, can you please fix the HDT description issue?

**Comment by swannie-eire** [comment]
@sirius-sama it will be a few weeks at least. Did staff say it to you?

I also found another issue with search returning invalid result. 

I find it best to search HDT with IMDB as it gives best results since IMDB link is required for each upload.

your code
![Screenshot 2023-08-30 at 8 19 54 a m](https://github.com/L4GSP1KE/Upload-Assistant/assets/57441681/6d36d468-152c-4e23-8b20-798d64886f7e)

my code
![Screenshot 2023-08-30 at 8 46 28 a m](https://github.com/L4GSP1KE/Upload-Assistant/assets/57441681/f84de89d-b4ef-4d1b-bfaf-57b9a77507c7)

**Comment by sirius-sama** [comment]
> it will be a few weeks at least. Did staff say it to you?

@swannie-eire No staff didn't say anything. I saw a forum post asking about the same thing How can we shrink the thumbnail size from any image host? No tags work, staff said they have no system for mentioning the thumbnail size on site explicitly. But I saw your torrent and description, I am really curious how you manage to have a thumbnail like that. You said you'll do that in August, but it's passing and I am curious to know how you did in that description, so I thought I should give you a reminder.

> I also found another issue with search returning invalid result.
> I find it best to search HDT with IMDB as it gives best results since IMDB link is required for each upload.

But I am passing IMDb id for every search. If id doesn't exist then use the title, that's how I wrote this dupe searching part. https://github.com/L4GSP1KE/Upload-Assistant/blob/eef529eed28e3a4ef167fa4b32ecfa8c77f9131f/src/trackers/HDT.py#L216C60-L216C60

**Comment by swannie-eire** [comment]
> > it will be a few weeks at least. Did staff say it to you?
> 
> @swannie-eire No staff didn't say anything. I saw a forum post asking about the same thing How can we shrink the thumbnail size from any image host? No tags work, staff said they have no system for mentioning the thumbnail size on site explicitly. But I saw your torrent and description, I am really curious how you manage to have a thumbnail like that. You said you'll do that in August, but it's passing and I am curious to know how you did in that description, so I thought I should give you a reminder. As you're saying it'll take time, so can you please share that desc with me? I am really curious to know how that worked.

Yeah I didn't realize then I would have a 50% of the drives in my raid array die within a week so this has held me up by at least at month. 


You can you the dev tools to see how I resize the images. If staff have not said anything then I wouldn't boder.

> 
> > I also found another issue with search returning invalid result.
> > I find it best to search HDT with IMDB as it gives best results since IMDB link is required for each upload.
> 
> But I am passing IMDb id for every search. If id doesn't exist then use the title, that's how I wrote this dupe searching part. https://github.com/L4GSP1KE/Upload-Assistant/blob/eef529eed28e3a4ef167fa4b32ecfa8c77f9131f/src/trackers/HDT.py#L216C60-L216C60
> 
> **EDIT**:
> 
> Ah, I just saw what you did, you passed IMDb with res and tag. I was just passing the IMDb. Btw, there are reasons for getting irrelevant dupe results. Like I was filtering by the download URL, that's why it's picking the sticky torrents. When I published this I said I would change that in the future because it was working fine. I should filter from the HTML table. Also, I didn't know that we could filter with IMDb and mix other things like res and tag. Indeed this would be more precise.

I don't actually use the sites search to check for dupes I use jackett as it means I can search any site but just passing the search filter and tracker ID from L4G into jackett. Its too time consuming to create a search function for each tracker hence why I use jackett. Plus on one site I spent 2 days trying to get their search API to work to only find out later it was broken. For that tracker it took 2 minutes to get it to search using jackett.

**Comment by sirius-sama** [comment]
> Yeah I didn't realize then I would have a 50% of the drives in my raid array die within a week so this has held me up by at least at month.

That sucks. Sorry to hear that :(

> You can you the dev tools to see how I resize the images. If staff have not said anything then I wouldn't border.
I checked before with dev tools and saw that the height was mentioned, I also checked other upload descriptions, and they didn't have a height attribute in their tag. I couldn't figure out how you mentioned the height in the [img] tag. 

The staff didn't say anything about this to me. I just want to fix this and am curious to know how you managed to do it.

> I don't actually use the sites search to check for dupes I use jackett as it means I can search any site but just passing the search filter and tracker ID from L4G into jackett. Its too time consuming to create a search function for each tracker hence why I use jackett. Plus on one site I spent 2 days trying to get their search API to work to only find out later it was broken. For that tracker it took 2 minutes to get it to search using jacket.

This Jackett thing sounds amazing. I will look into this later.

**Comment by sirius-sama** [comment]
@swannie-eire found out how to do it. I didn't know that this method only works on uploaded torrent descriptions, this doesn't work in the new upload page preview. Should I update the code?

**Comment by sirius-sama** [comment]
@swannie-eire Just an update, I found another issue about this, This doesn't fit 3 screens in a row if there is no proper aspect ratio. 
Either we've to use a small height or use 2 images in a row, or write an extra logic for this.

**Comment by swannie-eire** [comment]
> @swannie-eire Just an update, I found another issue about this, This doesn't fit 3 screens in a row if there is no proper aspect ratio. Either we've to use a small height or use 2 images in a row, or write an extra logic for this.

Yes you have to use a small height. I am currently using height == 137 as that is what i found the best results with.

**Comment by sirius-sama** [comment]
> Yes you have to use a small height. I am currently using height == 137 as that is what i found the best results with.

Yeah, 137 works best for 1080p and 720p height. But when there is 1920x800, or something around that, the 3rd image goes to the next line. It would be so much better if we could preview this before uploading.

So, a lower height would be better. Please take a look at whatever suits best for the situation and make changes.

**Comment by swannie-eire** [comment]
> > Yes you have to use a small height. I am currently using height == 137 as that is what i found the best results with.
> 
> Yeah, 137 works best for 1080p and 720p height. But when there is 1920x800, or something around that, the 3rd image goes to the next line. It would be so much better if we could preview this before uploading.
> 
> So, a lower height would be better. Please take a look at whatever suits best for the situation and make changes.

thats the limits of the site there is not really much point spending tonnes of time trying to get 3 screenshots per row. If you want you can add some logic to check screenshot size and change the height for the thumbnail based on that but its not something i would be willing to waste time on as no one has ever complained about it. 

The site only requires 2 screenshots so you can just use 2 screenshots if you want.

**Comment by sirius-sama** [comment]
Yeah, you're right. I asked you because you have been on that site for a long time, so you may know what'll be right to do.
No problem, I will take care of it then.
