### ISSUE TITLE
imdb error

### ISSUE THREAD

**Issue by HengeDK** [L4GSP1KE/Upload-Assistant#225]
any solutions for this error

`
CRITICAL [imdbpy] /home/xxx/.local/lib/python3.8/site-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt1430509/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 308: 'Permanent Redirect'>},); 
`

**Comment by swannie-eire** [comment]
try upgrading your cinemagoer as that is a bug with a previous version.

`pip install cinemagoer --upgrade`
