### ISSUE TITLE
Will uploading to EMP be possible?

### ISSUE THREAD

**Issue by Smoukus** [L4GSP1KE/Upload-Assistant#235]
Could the script be modified so that it works for EMP (empornium)?

**Comment by swannie-eire** [comment]
Isnt EMP a porn tracker? 

for Upload assistant(UA) to upload it needs data on the file its trying to upload from sites like TMDB, IMDB etc.. As i dont think that data will exist on indexers i dont think UA will ever be able to support EMP. Not unless there is a reliable indexer for porn and that indexer has an api that returns relevant data.

**Comment by L4GSP1KE** [comment]
No interest in supporting adult sites. A separate tool would likely be better suited for the task anyways.
