### ISSUE TITLE
ANT Screens

### ISSUE THREAD

**Issue by jonandeva** [L4GSP1KE/Upload-Assistant#238]
Just started using the assistant for ANT. I noticed that it doesn't seem to be adding any screens. Screens are optional there, but you can add 2, so if possible it would be nice to do that.

Thanks!

**Comment by karserasl** [comment]
Their API doesnt support links to screens.

> Input Parameters (all required):
> 
>     api_key - your API key
>     action = "upload"
>     tmdbid = film identifier from TMDb
>     mediainfo = newline-delimited mediainfo of the primary video file in the torrent
>     file_input = the torrent file
> 
> 
> 
> Optional Input Parameters: (use if your upload metadata can't be automatically determined from filenames / mediainfo; most times sending these parameters will auto-report uploads for manual review by staff)
> 
>     flags[] = array of site-supported flags, if not already present in the filename in mediainfo (supported flags: Directors, Extended, Uncut, Unrated, HDR10, DV, 4KRemaster, Atmos, DualAudio, Commentary, Remux, 3D, Criterion)
>     flagchangereason = text explaining presence of flags or other optional parameters; will be added to report as an explanation
>     lang = Original language of film if not present in first mediainfo audio section (do not send "English", "Multiple" or "Unknown")

**Comment by jonandeva** [comment]
> Their API doesnt support links to screens.

In the forums [where](https://anthelion.me/forums.php?action=viewthread&threadid=1025) they announce API support the question was asked. The developer responded:

> screenshots should work by including `screenshots` as an optional parameter and including up to 2 PNG URLs separated by a newline character (i.e. exactly what the upload form does).

**Comment by karserasl** [comment]
> 

Then they should have document it?

**Comment by jonandeva** [comment]
> > 
> 
> Then they should have document it?

I agree it is weird, but it would be convenient if it works.

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/09c6428a0f0dd46220e65828bb2dacc8a4b3a909
