### ISSUE TITLE
UHDHEAVEN

### ISSUE THREAD

**Issue by RikT** [L4GSP1KE/Upload-Assistant#24]
just checked this out and setup but on upload I am getting this error

{'success': False, 'message': 'Validation Error.', 'data': {'internal': ['The internal field is required.'], 'featured': ['The featured field is required.'], 'free': ['The free field is required.'], 'doubleup': ['The doubleup field is required.'], 'sticky': ['The sticky field is required.']}}

**Comment by L4GSP1KE** [comment]
hotfix up
