### ISSUE TITLE
HDB Screens are not thumbnails

### ISSUE THREAD

**Issue by jonandeva** [L4GSP1KE/Upload-Assistant#240]
HDB screens in description are not thumbnails.

Their BBCode instructions include the following:
<html><body>
<p class="sub">Image (resized)</p>
                            

Description: | Inserts a picture resized to 495px width.
-- | --
Syntax: | [imgw=URL]
Example: | [imgw=https://hdbits.org/pic/styles/default/logo.gif]

</body>
</html>

**Comment by L4GSP1KE** [comment]
Please use an image host with reasonably sized thumbnails, or their internal image host.

**Comment by jonandeva** [comment]
> Please use an image host with reasonably sized thumbnails, or their internal image host.

Thanks for the response. I was using ptpimg and it they were showing up as full sized images in the description. I would love to use their internal image host. Can it be set up in the upload assistant? I can't seem to find any info on that. If not, what might be a better image host? I'm just a bit confused because I haven't had an issue with screen thumbnails on any other tracker and I usually use ptpimg.

**Comment by jonandeva** [comment]
In case anybody else is wondering, I just added `"img_rehost" : True` to the config file and it uploads screens to HDB's image host.
