### ISSUE TITLE
Update for naming of TV Episodes

### ISSUE THREAD

**Issue by Kha-kis** [L4GSP1KE/Upload-Assistant#243]
episode_title_storage would be the prefered usage for the naming for tv episodes.

I see in BHD.py there is logic to update this.

```
        if meta['category'] == "TV" and meta.get('tv_pack', 0) == 0 and meta.get('episode_title_storage', '').strip() != '' and meta['episode'].strip() != '':
            name = name.replace(meta['episode'], f"{meta['episode']} {meta['episode_title_storage']}", 1)
```

Would it be possible to update the prep.py to use
          
`          episode_title = meta.get('episode_title_storage', '')`

as the default configuration?

**Comment by L4GSP1KE** [comment]
This is done on a per-site basis, and staff can reach out or include it in their rules if it needs to be added.
