### ISSUE TITLE
Naming request

### ISSUE THREAD

**Issue by austinwbest** [L4GSP1KE/Upload-Assistant#244]
So i have used my own upload script for awhile but i was going to give this one a shot and it seems to work except for the naming.

If i pick a season such as `/Some Series/Season 1` then it gets added to the client as `Season 1`

This will be very problematic when there are thousands of items all named `Season [0-9+]` so all i did for mine was take the folder name and add it to the the season name which makes the torrent name in the file `Some Series - Season 1`

Not sure if this is something you will entertain or not but if so i would surely use your script as it would be one less project i have to maintain lol

**Comment by L4GSP1KE** [comment]
Please name your folders appropriately, the script won't include an extra top level folder just for a series name or modify files for any reason. Nobody likes sorting through poorly named releases, or having them all downloaded into the same directory.

**Comment by austinwbest** [comment]
It is pointing it directly from my data drive so the folder names are correct for their current purpose. 

The point was not to need another folder and set of files and use it in another way. 

Thanks anyways, I'll just not use this.
