### ISSUE TITLE
error on dvdrips

### ISSUE THREAD

**Issue by FuNFooKaS** [L4GSP1KE/Upload-Assistant#25]
when trying to upload a dvdrip i get the following error
Gathering info for Bordertown.S01.DVDRip.x264-NODLABS
Exporting MediaInfo...
MediaInfo Exported.
Saving Screens...
* (1/6) Screens Saved
* (2/6) Screens Saved
* (3/6) Screens Saved
* (4/6) Screens Saved
* (5/6) Screens Saved
* (6/6) Screens Saved
DVDRip Detected, exiting

can this be fixedÉ

**Comment by L4GSP1KE** [comment]
This script does not support dvdrips

**Comment by FuNFooKaS** [comment]
well poop
