### ISSUE TITLE
Error Please enter a valid codec

### ISSUE THREAD

**Issue by SalmanZ9987** [L4GSP1KE/Upload-Assistant#252]
I am trying to upload a Blu-ray to a tracker.
The checking files step done 100%
Detects Mediainfo and BD info correctly
'Only Missing information it shows is --edition --region -- distributor but thats not important"
Creates screenshots and uploads 100%
Create .torrent file through hasing 100%

When uploading to tracker confirming 
1. Is this info the correct 'y' dupe check
2.  Dupe check upload anyways 'y'
Gives error {'error': 'Please select a valid codec.'}
*The torrent does not get uploaded to tracker due to this error*
And it skips to next step and adds .torrent file to tracker for seeding.

I have checked the /tmp/torrent for BD_FULL_00, BD_SUMMARY_00, BD_SUMMARY_EXT.txt all of them shows correctly identified Video, Audio codec with bitrates.

I have also checked meta.json where ever codec keyword is present correct information is there with bitrate and everything. Its not like it didnt obtain info or the info is missing.

What could this codec error be pointing to?

**Comment by sirius-sama** [comment]
Seems like the the codec field on the upload page not filling. 
Mentioning the tracker name would be better for the debugging.

**Comment by SalmanZ9987** [comment]
The Tracker is ANT

**Comment by SalmanZ9987** [comment]
I have talked to the Sysop of ANT and he pointed out. Its a issue on l4g side.
This is happeneing for Full Blu-ray Discs only i think.
Its not passing info in correct fields on tracker hence the error "Please enter a valid codec".
(If someone from your team wants to replicate it just take a Blu-ray Full Disk and try to upload it)

**Comment by ahopelesshadow** [comment]
I have looked into this from Anthelion's end, and have identified the issue.  Im working with L4G on a fix, this would actually effect bdmv as well as dvd video_ts dumps from what I can tell.  I think I only need to make edits to ant.py which I will provide to L4G when complete, but that depends on the data contained in the meta dict passed to the upload module.  I may end up PR'ng this if I need to add more information.  Will update Soon TM

//Kitty
//ANT SysOp

**Comment by SalmanZ9987** [comment]
Ok, Thank You. I'll leave this open for now so when you are done you can update here.

**Comment by ahopelesshadow** [comment]
Please note this is an extremely quick edit just to show it works, and I will clean this up further in the future, but replacing ANT.py in root/src/trackers with the following, will fix bdmv full disk uploads.  I have not yet tested DVD full disks, and may change this again in the future, but this is better than nothing for now. :)
rename to ANT.py since i cant attach py files.

[ANT.py.txt](https://github.com/L4GSP1KE/Upload-Assistant/files/12864162/ANT.py.txt)

**Comment by SalmanZ9987** [comment]
Thanks for the quick fix. I am closing this hopefully DVD full disks also gets added too and included in the offilcial git release. For now like you said this will work and you can possibly post the updated (with DVD Full disks) file in ANT threads.
Thank you again :)
