### ISSUE TITLE
Torrent rehash in case of wrong base piece size

### ISSUE THREAD

**Issue by shapelessvoid** [L4GSP1KE/Upload-Assistant#256]
Hi,

I'm looking this code snippet here: https://github.com/L4GSP1KE/Upload-Assistant/blob/master/src/prep.py#L2002
It seem to me that this line is wrong. Shouldn't we write the newly generated `.torrent` file to
 `f"{meta['base_dir']}/tmp/{meta['uuid']}/{output_filename}.torrent"` 
instead of 
`f"{meta['base_dir']}/tmp/{meta['uuid']}/BASE.torrent"` 
as we do for other tools above beside torf? 

The current implementation produces a `File not found` exception in `MTV` tracker implementation right here: https://github.com/L4GSP1KE/Upload-Assistant/blob/master/src/trackers/MTV.py#L87 .

**Comment by mlapaglia** [comment]
happens to me also. re-running the script it picks the newly made torrent file up and uploads it correctly.

**Comment by shapelessvoid** [comment]
> happens to me also. re-running the script it picks the newly made torrent file up and uploads it correctly.

The above change fixed it for me. You can try it and share back if it works for you. It's simple enough until it's fixed in the upstream.

**Comment by L4GSP1KE** [comment]
Thanks! https://github.com/L4GSP1KE/Upload-Assistant/commit/ad8f6d66702b03b8499a150b076a1f438768189f
