### ISSUE TITLE
HDB Audio in Title

### ISSUE THREAD

**Issue by jonandeva** [L4GSP1KE/Upload-Assistant#260]
On HDB moderators do not allow a space between audio codec and number of channels. (ie AAC 2.0 should be AAC2.0) I've received a few messages for that. Could this be fixed?

Also, FYI, I know this doesn't work on BTN, but they have the same naming rule.

Thanks for all you do!

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/10ef647ac90b2d8b8441c56551a25328ab6e4597
