### ISSUE TITLE
Request for Aither

### ISSUE THREAD

**Issue by mnejing** [L4GSP1KE/Upload-Assistant#265]
Any chance you can add an option for Aither to toggle the Personal Release option? I think it'd be handy.

**Comment by mesoller** [comment]
--personalrelease flag should work. I'm using this flag for Aither

**Comment by mnejing** [comment]
Oh neat, I was looking through examples and must have missed that entirely.

**Comment by AllegedlyUndead** [comment]
You can also add your tag to tags.json.

{
	"your_tag_here" : {
                "personalrelease" : "True",
	}
}

**Comment by mnejing** [comment]
Thanks for the responses, this is exactly what I was hoping for. Closing issue.
