### ISSUE TITLE
Feature Request - mod existing torrent instead of creating a new one.

### ISSUE THREAD

**Issue by swannie-eire** [L4GSP1KE/Upload-Assistant#28]
So currently the script generates a new torrent and this does not seem optimal to me as most of the time you will have the torrent from another indexer. If its a large file/data it can take a while to create the torrent and this can take up resources.

Instead of creating a new torrent it would be better to just mod the existing torrent as most indexers use the source field and that is all that is required to generate a new torrent to have a unique hash. 

I am hoping so instead of passing path to file we can pass path to file and an existing torrent for this and it will then just mod the torrent and get screens, get info, upload and add to torrent client.

**Comment by L4GSP1KE** [comment]
`-th` / `--torrenthash` now accepts the infohash and will search a predefined session folder for an existing torrent. This needs mods to your config, adding `torrent_storage_dir` to your torrent clients https://github.com/L4GSP1KE/Upload-Assistant/blob/b931ce900d3095877893d2fc4372d3ee057169d5/data/example-config.py#L97
