### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by KingMak3r** [L4GSP1KE/Upload-Assistant#284]
Hi everyone! 

Well I feel like Im missing something very basic here and would appreciate any guidance you may have on this error. 

Alright, Im installing Upload-Assistant on Windows 10, installed Python/pip/MediaInfo/ffmpeg, added to PATH accordingly, renamed & edited config.py and installed necessary python modules. 

I receive the following error when running ``` C:\Users\USER1\Downloads\OldTV\Early.Edition.S02 or python upload.py --help```: 
```
C:\Users\\Upload-Assistant>python upload.py
Traceback (most recent call last):
  File "C:\Users\\Upload-Assistant\upload.py", line 4, in <module>
    from src.prep import Prep
  File "C:\Users\\Upload-Assistant\src\prep.py", line 5, in <module>
    from src.trackers.PTP import PTP
  File "C:\Users\\Upload-Assistant\src\trackers\PTP.py", line 5, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils'
```

This feels like a python error but I could be wrong. Thanks in advance for the support.

**Comment by swannie-eire** [comment]
You don't have distutils installed. 

`pip install distutils`

Run that command and it should install for you.

**Comment by KingMak3r** [comment]
Thank you swannie-eire! You got me to the right solution. It didn't work exactly but made me look at installing distutils. 

```
pip install distutils
```  
**but:**
```
py -m pip install --upgrade pip setuptools wheel 
```
worked for me!

Thanks again
