### ISSUE TITLE
Image Upload Error

### ISSUE THREAD

**Issue by KingMak3r** [L4GSP1KE/Upload-Assistant#286]
Hey Everyone!

I'm back with a question on a basic error that I haven't figured out yet. So, every now and then when I upload to PTP I get an error after uploading my screenshots. I have ptpimg set as my first image host and after every couple of uploads I get this error. For example, when I run: ``` python upload.py C:\Users\X\[RaX]Blade_of_the_Phantom_Master_(x264_AAC)_[1C3A2140].mkv``` 

Screenshot creation and ptpimg upload fail results: 

<details><summary>Details</summary>
<p>

```
Gathering info for [RaX]Blade_of_the_Phantom_Master_(x264_AAC)_[1C3A2140].mkv
Exporting MediaInfo...
MediaInfo Exported.
Searching PTP for: [RaX]Blade_of_the_Phantom_Master_(x264_AAC)_[1C3A2140].mkv
Could not find any release matching [RaX]Blade_of_the_Phantom_Master_(x264_AAC)_[1C3A2140].mkv on PTP
Saving Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 0:00:00
ptpimg failed, trying next image host
Uploading Screens... --------------------------------- ------ 5/6 -:--:--
Uploading Screens to Imgbox...
Missing torrent_storage_dir for Client1
Creating .torrent with a piece size of 512KiB... (No valid --torrenthash was provided to reuse)
Prep material saved to C:\Users\X\Upload-Assistant/tmp/[RaX]Blade_of_the_Phantom_Master_(x264_AAC)_[1C3A2140].mkv

``` 

</p>
</details> 

Error after choosing PTP as the tracker:
<details><summary>Details</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\X\Upload-Assistant\upload.py", line 406, in do_the_thing
    await ptp.upload(meta, ptpUrl, ptpData)
  File "C:\Users\X\Upload-Assistant\src\trackers\PTP.py", line 838, in upload
    raise UploadException(f"Upload to PTP failed: {errorMessage} ({response.status_code}). (We are still on the upload page.)")
src.exceptions.UploadException: Upload to PTP failed: <div>Please don't hotlink images from ImageBam, imgbox and SomeImage.<br>Only thumbnailed image links are allowed from these sites.<br><br>ptpimg.me is recommended for hosting the images.<br>ImageShack, imgur, Postimage and TinyPic are not allowed. (200). (We are still on the upload page.)
None
``` 

</p>
</details> 

My observation is that no image is uploaded to ptpimg (this is reported in the error) and that the file upload is sent to the next host on my list. However, Im not sure why  its failing to upload to imgptp.

Thanks!

**Comment by sirius-sama** [comment]
Make sure your ptpimg API key is correct in your config.py file.

**Comment by KingMak3r** [comment]
**Hey sirius-sama,**

That was my initial thought as well. But I've uploaded numerous torrents through Upload Assistant on multiple trackers with the imghost set to ptpimg (it only fails occasionally). If it was an issue with the api_key it would fail every time, right?

**Comment by sirius-sama** [comment]
Yes, it would fail every time.
I have seen downtimes of ptpimg recently. Sometimes image uploading becomes too slow even if the site is up, sometimes it is stuck at uploading only 1 image for a while. So, most likely this is a problem from ptpimg's side.

**Comment by KingMak3r** [comment]
That could be it. Thanks
