### ISSUE TITLE
Doest upload

### ISSUE THREAD

**Issue by RikT** [L4GSP1KE/Upload-Assistant#29]
Just Updated this and now it doesnt upload its get to the naming stage press y it aborts from there
![Untitled](https://user-images.githubusercontent.com/732290/154276076-91c5d830-a771-481c-b569-0a750d8166e2.png)

**Comment by swannie-eire** [comment]
i just tested and it works fine. 

Are you sure you have trackers specified to upload to in your config because if you dont you get what you see.

you should have the trackers you want to upload to listed in default trackers. It will ask you to confirm before you upload to those sites.

e.g
```
    "TRACKERS" : {
        # Which trackers do you want to upload to?
        #"default_trackers" : "BLU, BHD, AITHER, STC, THR, UHDHEAVEN, R4E",
        "default_trackers" : "BLU, BHD",

**Comment by RikT** [comment]
it was working before update and its happened on 2 servers so must be the update thats broken it for my site

**Comment by L4GSP1KE** [comment]
Thanks RikT, turns out I introduced a bug where it wouldn't work if you only had one tracker specified. This should be fixed now

**Comment by RikT** [comment]
nope still  got errors it searches for dupe then just get message it may have uploaded and has not see pic below
![Untitled](https://user-images.githubusercontent.com/732290/154372463-7bbee9f3-b453-40b6-8300-93cd762ec1b6.png)

**Comment by L4GSP1KE** [comment]
try again k thx :)
