### ISSUE TITLE
MTV

### ISSUE THREAD

**Issue by MasalaTalk** [L4GSP1KE/Upload-Assistant#302]
Please keep MAX piece size for torrent hashing at 8MB. have to do twice for every torrent. too much time waste.

**Comment by mesoller** [comment]
Good suggestion. But for me, I just set for all trackers max at 8MB

**Comment by MasalaTalk** [comment]
> Good suggestion. But for me, I just set for all trackers max at 8MB

how  ?

**Comment by mesoller** [comment]
Add flag --piece-size-max 8

**Comment by MasalaTalk** [comment]
thanks it works :)
