### ISSUE TITLE
New tracker: Alpha Ratio [AR]

### ISSUE THREAD

**Issue by AN1MATEK** [L4GSP1KE/Upload-Assistant#323]
While not a new tracker, AR is a great entry point for many users trying to "climb the ladder" in the PT world. It think it could be a great addition to this script.

I found a outdated python script that probably has almost that's needed. It is to complex for me to understand, but it is a start.

https://github.com/TnS-hun/PtpUploader/blob/master/src/PtpUploader/Source/AlphaRatio.py

Thank you.

**Comment by swannie-eire** [comment]
Already a issue open for it.

https://github.com/L4GSP1KE/Upload-Assistant/issues/261

Please see my comment in that issue for details while this will probably be slow to be implemented.

**Comment by AN1MATEK** [comment]
Thank you for pointing it out. I though I searched but obviously not good enough.
