### ISSUE TITLE
[Request] Link to raw image in description when using imgbb

### ISSUE THREAD

**Issue by stuffwatcher** [L4GSP1KE/Upload-Assistant#338]
Would it be possible to do that?

**Comment by swannie-eire** [comment]
You can find the raw image links in tmp/<filename>/meta.json


Raw images are not used in descriptions by default as they are against many sites rules and sometimes they can be huge and cause pages to ages to load for people with slow connections.

Thumbnails are displayed by default for most sites and if you click the thumbnail it will bring you to the raw image.

**Comment by stuffwatcher** [comment]
Sorry I wasn't clear, I didn't mean to replace the thumbnails but replace the actual link to link directly to the PNG, example:
Replace https://ibb.co/N7ZHNZp by https://i.ibb.co/1b8wX8K/3b310263996e.png

**Comment by sirius-sama** [comment]
> Sorry I wasn't clear, I didn't mean to replace the thumbnails but replace the actual link to link directly to the PNG, example: Replace https://ibb.co/N7ZHNZp by https://i.ibb.co/1b8wX8K/3b310263996e.png

You can achieve this by simply changing all the ``web_url`` to ``raw_url`` in your service.py file.

EDIT: If you want this only for imgbb, then you have to write an if-else condition for when the images are hosted on imgbb.

**Comment by stuffwatcher** [comment]
Thanks! I ended up changing `prep.py` to set imgbb `web_url` to same thing as `raw_url`.
