### ISSUE TITLE
Feature request - remove duplication of medainfo checking.

### ISSUE THREAD

**Issue by swannie-eire** [L4GSP1KE/Upload-Assistant#34]
Currently if you run the script it checks the mediainfo, takes screens and uploads the screens to a picture host.

If you run the script again on the same torrent it checks the mediainfo again but does not take and upload screens which is good but as the mediainfo was already checked and saved i think should this be skipped too as for larger files on networked drives it can take a while to get the media info.

![Screenshot 2022-03-02 at 12 00 43](https://user-images.githubusercontent.com/57441681/156357889-5b0fa2de-04ef-48a5-b330-6589cc3fdfa8.png)

**Comment by L4GSP1KE** [comment]
Implemented
