### ISSUE TITLE
[DEFECT] - if existing torrent used trackers are not removed if more than one tracker per teir.

### ISSUE THREAD

**Issue by swannie-eire** [L4GSP1KE/Upload-Assistant#37]
If you are trying to upload an existing torrent that has more than one tracker the trackers are not removed when uploading to a new site.

Many trackers such as IPT have multiple trackers in their torrents if you try to upload one of those torrents. using the -th option the torrent that is uploaded will contain the trackers from the original torrent and the new tracker/s will not be added.

steps to dupe.

1. download or create a torrent with multiple trackers per tier.
2. run upload script with hash of torrent.
```python3.8 upload.py /path/to/file -th <existing-torrent-hash>```
3. upload to any tracker that the script supports. probably best to use BHD as you can upload as draft.
4. Check your torrent client and you will see the new torrent has been added but it has the trackers from the original torrent instead of BHD.
5. Check the torrent in the tmp dir with torf -i and you will also see that the new torrent has the trackers from the original torrent.
 
if you remove one of the trackers it works perfectly.

![Screenshot 2022-03-07 at 13 36 41](https://user-images.githubusercontent.com/57441681/157044675-fc08d4b3-8b18-441f-b006-3cea84bf5918.png)

![Screenshot 2022-03-07 at 13 37 13](https://user-images.githubusercontent.com/57441681/157044667-1b5d1c3e-27c3-4450-89d5-381fe78b4436.png)

**Comment by L4GSP1KE** [comment]
Many thanks! It should also remove the publisher and publisher-url fields as well

fixed in: https://github.com/L4GSP1KE/Upload-Assistant/commit/ece1dbe4d81177c90a4ec678a1ef516f5c4069a2

**Comment by swannie-eire** [comment]
> Many thanks! It should also remove the publisher and publisher-url fields as well
> 
> fixed in: [ece1dbe](https://github.com/L4GSP1KE/Upload-Assistant/commit/ece1dbe4d81177c90a4ec678a1ef516f5c4069a2)

thanks for fixing so fast. Never heard of the publisher and publisher-url fields so no wonder i wasnt able to fix it myself.
