### ISSUE TITLE
Feature request - abiltiy to disable AKA naming

### ISSUE THREAD

**Issue by argonan0** [L4GSP1KE/Upload-Assistant#38]
Should be an argument `-noaka` for example to disable multiple naming, specifically for anime. If that's necessary to identify the mal_id, should also be another argument to specify mal_id, `--malid xxx` for example.

**Comment by L4GSP1KE** [comment]
I can't think of a good reason to purposefully hinder search-ability, especially for foreign content. But I have added `--mal 123` because that was a good idea! Thanks!
