### ISSUE TITLE
Support for [STT] Skipthetrailers Unit3d Tracker

### ISSUE THREAD

**Issue by swannie-eire** [L4GSP1KE/Upload-Assistant#43]
[Skipthetrailers](https://skipthetrailers.xyz/) is unit3d based.

i wrote the code and it can be found here https://github.com/swannie-eire/ua-trackers/blob/main/STT.py. I changed the forum link to rules since you dont mention L4G on the site.

i only tested a few uploads and all seemed to work and check for dupes so if you come across any issues let me know

If you need an invite to test please let me know.

you will of course need to update the config and upload.py to use it.

**Comment by kraljetera** [comment]
In rTorrent its red and I get message Tracker: [Failure reason \"Passkey does not esist! Please Re-download the .torrent\"]

...what do I do wrong?

**Comment by L4GSP1KE** [comment]
@swannie-eire thanks for the work, I've dropped it in and it _should_ work as intended. Please test and close issues / report/PR any fixes needed.

**Comment by swannie-eire** [comment]
> In rTorrent its red and I get message Tracker: [Failure reason "Passkey does not esist! Please Re-download the .torrent"]
> 
> ...what do I do wrong?
> 
> PS After I download manually works fine!

i dont use rTorrent but have you checked the passkey/announce Url in the one Upload-Assistant adds to rtorrent compared to the one in the torrent that you added manually.
