### ISSUE TITLE
[DEFECT] - united template has wrong filter.

### ISSUE THREAD

**Issue by swannie-eire** [L4GSP1KE/Upload-Assistant#45]
in the template it has ```response = requests.get(url=self.filter_url, params=params).``` when i use it i get an exception. When i use ```response = requests.get(url=self.search_url, params=params)``` which is in other unit3d trackers. it works as expected. 

it looks like the filter_url does not exist.

my HP vs existing
![Screenshot 2022-03-24 at 15 00 38](https://user-images.githubusercontent.com/57441681/159946240-2c2f4ea2-1731-4448-b375-b0d52e0dcb67.png)

the search in the recently added HP does not work as a result of this.

**Comment by L4GSP1KE** [comment]
Thanks! Fixed (https://github.com/L4GSP1KE/Upload-Assistant/commit/2ebe2373aedfd1d1e6df27216bef937d9870929a)
