### ISSUE TITLE
Remote pathing drive letters are case sensitive

### ISSUE THREAD

**Issue by YourHuckleberry** [L4GSP1KE/Upload-Assistant#47]
My config was set as:

"local_path" : "Z:\\download",
"remote_path" : "/config/download"

Using a lower case z: in command line to run the script results in the path not matching and the torrent uploaded to my client had both paths appended together.  Good to go now, but I was scratching my head for twenty minutes trying to figure out why it wasn't working.

**Comment by L4GSP1KE** [comment]
Probably fixed with (https://github.com/L4GSP1KE/Upload-Assistant/commit/46eb995c279ea94b8c7bda6f642173c5c45d3d53).  I've also added notes in the example config stating remote paths are case sensitive
