### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by rj-d2** [L4GSP1KE/Upload-Assistant#5]
Hi, im trying to upload to BHD,

readme:
```
  -client, --client       Override default torrent client
  -tk, --trackers         Override default torrent client
```

i think there is a typo and -tk means default tracker,

i tried:

python3 /.../upload.py path/to/file -tk BHD
python3 /.../upload.py path/to/file --trackers BHD

the script asks me if i want to upload to BLU i select no and it quits.

whats the correct ARG to only upload to BHD?
is the upload to the drafts folder of BHD or is the torrent going live immediately?
is it possible to get other trackers included in the script? (HDT, TDB, MTV when its fully back)

thx for your work!!

**Comment by L4GSP1KE** [comment]
yeah uhh I haven't finished building out BHD quite yet, I just pushed small config changes and the start to the BHD module. Expect a forum post there sometime soonish when i finish it. As for the other trackers, if they have a decent upload/torrents api I might add them eventually. PRs are always welcome though

**Comment by L4GSP1KE** [comment]
There's a post on the BHD forums now if you haven't seen it yet
