### ISSUE TITLE
Passing 0 as IMDB ID on PTP results in an error

### ISSUE THREAD

**Issue by eac4** [L4GSP1KE/Upload-Assistant#53]
The error message is huge, the important part of it is `IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0000000/reference', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 404: ''>},)`. Usually when IMDB doesn't exist, you put a 0 in that field on PTP. Here the script attempts to access a noneexistent IMDB page. I tried a simple hack `meta['imdb_info'] = ({} if meta['imdb_id'] == '0' else await prep.get_imdb_info(meta['imdb_id']))`, which let me continue but then on finalizing it received another error `src.exceptions.UploadException: Upload to PTP failed: <div>You must enter at least one tag. Maximum length is 200 characters. (200). (We are still on the upload page.)`. In the case of my movie, the tag exists on tmdb, but since PTP only uses IMDB i'm guessing the script ignored TMDB info entirely. Ideally it would be taken into account too, but an easier option would be to add a custom tag arg to the `Input args that need correction`

**Comment by swannie-eire** [comment]
im not sure what tag is suppose to be as i dont have access to PTP but I would assume keywords. If thats the case you can just use the tags from the script that it gets from TMDB. e.g meta['keywords']

**Comment by eac4** [comment]
Seems to work consistently with new changes, cheers all.
