### ISSUE TITLE
Feature Request - reduce bit depth of massive screenshots

### ISSUE THREAD

**Issue by hldr4** [L4GSP1KE/Upload-Assistant#55]
On 10-bit 4K video, especially HDR/DV stuff the screenshot size can get quite enormous, which some users/trackers don't like. Would it be possible to add (possibly via a flag) reduction of bit depth to 8 on those if they exceed a certain size, say 20mb. ImageMagick is able to do this via a simple command `magick convert in.png -depth 8 out.png`. Also taking the opportunity here to report a small related bug - 10-bit SDR content doesn't get 10-bit added to edition information on PTP.

TIA

**Comment by swannie-eire** [comment]
@L4GSP1KE i assume this is done since its closed?

Do we need to specify how to reduce bit depth with arg as i dont see any obvs args for it.
