### ISSUE TITLE
Force a category

### ISSUE THREAD

**Issue by gamemnon** [L4GSP1KE/Upload-Assistant#56]
Hello,

How to force a category ? got a category anime same as tv for meta, but not same content.
If i add category to mytk.py thats dosnt work at all :-/

**Comment by gamemnon** [comment]
Hi, 

i see this `            if meta.get('anime', False) == False:
                meta['mal_id'], meta['aka'], meta['anime'] = self.get_anime(response, meta)
`
in the code how use it to rewrite category_id to put it on the right category ?

**Comment by L4GSP1KE** [comment]
sorry for late response, but here's an example of a unit3d site that has an anime category
https://github.com/L4GSP1KE/Upload-Assistant/blob/ea8e6622d01e873e38d96185924a8cef914c3789/src/trackers/LCD.py#L121-L122
