### ISSUE TITLE
allow evo for ptp

### ISSUE THREAD

**Issue by greeneryAO** [L4GSP1KE/Upload-Assistant#61]
certain evo rips the h264 webdls are allowed in ptps rules, but trying to upload any evo it gives a message and denies the upload, if the person is stupid and didn't read rules of which are allowed then that's their fault but people following rules should be allowed to upload site ok content without that message.

**Comment by L4GSP1KE** [comment]
I do nothing to allow or deny any specific release groups, including EVO. If the script says that the upload has been denied, it means that the site has rejected the upload

**Comment by greeneryAO** [comment]
oh sorry then, I thought it was coming from your side but thought it also possible it was them, guess I'll talk to them, maybe 🤨

regards.
