### ISSUE TITLE
how can I rename files?

### ISSUE THREAD

**Issue by greeneryAO** [L4GSP1KE/Upload-Assistant#65]
whenever I try to rename a file with an ( in it or DVDrip even though my tracker allows it, if I rename through qbit or a linux explorer and point to video it says path error empty or all files exluded, even though I'm pointing right at it, if I leave everything as it came it works but not all files are like that some have naming errors etc.

**Comment by neoxcrazy** [comment]
try delete content of tmp folder.

**Comment by greeneryAO** [comment]
tried deleting everything related to a test movie in the tmp folder, it creates screens then after uploading, errors, darn was hoping that would work because tmp folder has a lot of crap.

**Comment by L4GSP1KE** [comment]
I'm not understanding the issue here, do you have any more information?
Also the script does not support dvdrips

**Comment by greeneryAO** [comment]
I think it's a nonissue, because some files did allow me rename and some didn't, so I can't blame the renaming on it, mostly low quality junky avi rips I was trying to rename and upload were giving me that error code of not seeing the file despite posting it, but I stopped with that sourcing, and most of my files work fine.

also learned you can single quote to upload ( marks so it's only a few files, but the script errors occasionally on resolutions it doesn't like etc anyway on mkvs named properly, not perfect but sure handy.

so all good.
