### ISSUE TITLE
[REQ] Make it easier to be used for other trackers

### ISSUE THREAD

**Issue by waldens** [L4GSP1KE/Upload-Assistant#7]
Thank you for letting this script work perfectly on Windows as well!

I use your script to generate .torrent file, screenshots and mediainfo in tmp subfolder with just one command (brilliant!). Although the description and other info scraped from IMDB/TMDB (plot etc) still have to be done manually (after selecting N for both "Upload to xx? (y/N)", the script will auto exit with only generating an empty DESCRIPTION.txt), but still much more convenient than completely manual.

It would be more perfect if:
* DESCRIPTION.txt could also be auto generated successfully, even if not used for BHD and BLU (include generic info, eg cast list, IMDB/TMDB links, ratings, etc., like [this format](https://i.imgur.com/Jvc8bED.png) or [this](https://i.imgur.com/a5DmcPz.png))
* Print the result PTPimg URLs on the console, or even better, under tmp subfolder.
* Output the movie poster grabbed from IMDB/TMDB, under tmp folder.

So that when being used for other trackers, the script generates all the generic materials (not tracker specific) in the tmp folder and user just need to do the copy/paste work and make minimal modifications on the webpage of any tracker they wanna upload to.

This will allow the script to benefit more people and trackers, while not making the maintenance workload too higher (maintaining different upload APIs for different sites)

**Comment by L4GSP1KE** [comment]
For now I've added a GENERIC_INFO.txt if to the `-m`/`--manual` functionality that should make it easier to copy paste imdb/tmdb/etc for people that use it like you do. I don't see myself adding things like cast lists/ratings/etc until i end up somewhere that needs it because I honestly think the tracker should be able to populate that data itself

**Comment by waldens** [comment]
@L4GSP1KE Just tried, works like a charm! :+1: 

Only one thing, could [this part of info](https://i.imgur.com/S9TPXIo.png) (esp the overview text) also be exported to GENERIC_INFO.txt? So that all the raw info materials needed for uploading on other trackers are complete!

UNIT3D trackers like BLU and BHD can deal with cast lists/ratings/etc on their own, but sadly old sites like CG or Gazelle sites like bB/Secret-Cinema cannot deal with these infos, need to be filled in the description part by the uploader themselves. But anyway, no biggie, the script now is already brilliant enough (among the many auto-upload scripts, the only one that works smoothly on windows), Big thanks.

**Comment by L4GSP1KE** [comment]
Done.

**Comment by waldens** [comment]
@L4GSP1KE  Thx
BTW, just found exit on dvdrip commit. It makes sense for this script to ban DVDRip since BHD/BLU both ban it, but on sites like CG/bB/SC (and PTP allegedly), DVDRip is allowed. But no biggie since user can remove those 3 lines on their own if really needed. Thanks for such a quick response and fix. :)
