### ISSUE TITLE
Script not treating errors when upload fails

### ISSUE THREAD

**Issue by costaht** [L4GSP1KE/Upload-Assistant#70]
Hi, https://imgbox.com/ is down and we noticed that some posts descriptions started showing up with broken image links. On my tests, I couldn't really find a pattern, but after failing to upload the screenshots to one of the providers, the script still generates the image tags with "None" as addresses

```
Uploading Screens to Imgbox...
[
    {'web_url': None, 'img_url': None, 'raw_url': None},
    {'web_url': None, 'img_url': None, 'raw_url': None},
    {'web_url': None, 'img_url': None, 'raw_url': None},
    {'web_url': None, 'img_url': None, 'raw_url': None},
    {'web_url': None, 'img_url': None, 'raw_url': None},
    {'web_url': None, 'img_url': None, 'raw_url': None}
]
Creating .torrent
```

which results in:
```
[img=350]None[/img]
[img=350]None[/img]
[img=350]None[/img]
[img=350]None[/img]
[img=350]None[/img]
[img=350]None[/img]
```
My understanding is that the script should skip the image uploading, stop the whole uploading process or prompt the user for a decision.

**Comment by L4GSP1KE** [comment]
yes https://github.com/L4GSP1KE/Upload-Assistant/commit/6a6fdf161844dc7a4ba50f6f44fed76f9d7f9d01
