### ISSUE TITLE
Single file - incorrect folder in Deluge

### ISSUE THREAD

**Issue by Skamba** [L4GSP1KE/Upload-Assistant#75]
When I upload a single file, the directory is incorrectly set in Deluge and therefore it cannot find the file.

Command used:
`python3 upload.py /mnt/3tb/ptpuploads/Be.Human.1936.576p.Opus.x264.mkv -pr
`

Directory mapping in the config for Deluge:
```
           # Remote path mapping (docker/etc.) CASE SENSITIVE
            "local_path" : "/mnt/3tb/ptpuploads",
            "remote_path" : "/3tb/ptpuploads"
```
Resulting torrent in Deluge:
![image](https://user-images.githubusercontent.com/8420201/183944864-e8d9e690-aad1-4968-9ec6-c2c99bc87a4e.png)

The download folder should be set to '/3tb/ptpuploads/' for a single file, rather than '/3tb/ptpuploads/Be.Human...'

**Comment by L4GSP1KE** [comment]
I've made a change to where deluge adds the file. Let me know if this works

**Comment by Skamba** [comment]
Seems to have fixed it!
