### ISSUE TITLE
Region arg not getting passed if meta.json already exists

### ISSUE THREAD

**Issue by Tekkeye** [L4GSP1KE/Upload-Assistant#79]
Greetings,

I recently attempted to upload a full disc without passing the `--region` arg, but then ended up not uploading it then and there. A few days later, I re-ran the script on the same disc content but this time I passed `--region` as an argument. It did not however adjust the name of the upload to include the region provided; it simply used the title that was generated when I first ran the script.
This issue was resolved upon deleting tmp/<filename>/meta.json and re-running the script. Another user mentioned to me that this was not a problem until recently so thought I would bring it up.

Thanks

**Comment by L4GSP1KE** [comment]
Fixed. Thanks!
