### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by daomengRen** [L4GSP1KE/Upload-Assistant#8]
hi is this an upgraded version of BluUpload, because I stared it before, but now it is gone. In addition, what trackers does this tool support? Finally, thank you for your script

**Comment by L4GSP1KE** [comment]
> hi is this an upgraded version of BluUpload, because I stared it before, but now it is gone. 

Yes.




>In addition, what trackers does this tool support? Finally, thank you for your script
Currently it works with BLU/BHD, because they're what I have access to. I do accept PRs if you wish to add other trackers. The script also has an options to return screens/mediainfo/etc. if you wish to do your upload manually

**Comment by daomengRen** [comment]
ok thanks
