### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by BradleyRL** [L4GSP1KE/Upload-Assistant#81]
Im trying to use the discord bot, everything is set up correctly, but when I run the bot 
 python3 discordbot.py

dunno if thats correct I get this error

`/root/Upload-Assistant/discordbot.py:112: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "/root/Upload-Assistant/discordbot.py", line 113, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/Upload-Assistant/discordbot.py", line 25, in run
    bot = Bot(config=config,
  File "/root/Upload-Assistant/discordbot.py", line 35, in __init__
    super().__init__(
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'
`

**Comment by BradleyRL** [comment]
Its related to [Intents](https://discordpy.readthedocs.io/en/latest/api.html?highlight=client#discord.Intents) are now [required](https://discordpy.readthedocs.io/en/latest/api.html?highlight=client#discord.Client) in discord.py==2.0.0

**Comment by L4GSP1KE** [comment]
Yes. I'm aware the discord bot does not work. It's been untouched for months and needs a rewrite eventually™

**Comment by borxR** [comment]
will there be an update to the discord code soon?

**Comment by L4GSP1KE** [comment]
Consider the discord bot abandoned
