### ISSUE TITLE
[Feature Request] Re-use Uploaded Images

### ISSUE THREAD

**Issue by costaht** [L4GSP1KE/Upload-Assistant#82]
If for some reason we have to abort an upload after the upload of the screenshots was done, Upload-Assistante will reuse those screenshots, but not the links that it already received from the image hosting website.
Would it be possible to re-use those links? That will save us some time. 

Thanks

**Comment by L4GSP1KE** [comment]
uploaded images are saved upon reaching the confirmation prompt and will be reused on any reruns after that point.
