### ISSUE TITLE
-pr flag causes wildcards to fail

### ISSUE THREAD

**Issue by costaht** [L4GSP1KE/Upload-Assistant#85]
If you try to use any wildcard combined with the `-pr`, it will fail to find the files/folders.

Without `-pr` flag:

![Screenshot from 2022-08-29 17-00-19](https://user-images.githubusercontent.com/50637431/187298060-fd753e66-3a5c-4c76-bd0d-a23517768932.png)
![Screenshot from 2022-08-29 17-00-08](https://user-images.githubusercontent.com/50637431/187298061-5bfe4145-4a19-4ad2-92df-aa35e825784d.png)

With `-pr` flag:

![Screenshot from 2022-08-29 17-00-19](https://user-images.githubusercontent.com/50637431/187298070-1345049d-6cf1-4e40-b6a2-53d8424261b0.png)

**Comment by L4GSP1KE** [comment]
am i missing something?

**Comment by costaht** [comment]
Sorry, hahaha I just realized I uploaded the wrong pic

**Comment by costaht** [comment]
Basically the second was shows empty match and quits

**Comment by L4GSP1KE** [comment]
oh I'm dumb, The path needs to be provided first. Doing `upload.py Swamp.People.S0* -pr` would work as intended
