### ISSUE TITLE
[Feature Request] Add config value for enabling Automatic Torrent Management in Qbit

### ISSUE THREAD

**Issue by milkdawg** [L4GSP1KE/Upload-Assistant#86]
I use automatic torrent management to categorize my files for long term seeding.

Would it be possible to allow automatic torrent management given its possible in scenario.

In my head would like like 2 additions to config file

- default save path (ex. /downloads)
- use auto torrent management if possible (true/false)

and then when adding to qbit check if auto torrent management config value is true and torrent save path matches the default save path, then enable flag in qbt_client.torrents_add.

If this is something you would be ok with, I can make a PR if you dont want to do it and do it myself.  Implementation would be rather trivial I think hence the issue instead of just plain PR.

**Comment by L4GSP1KE** [comment]
https://github.com/L4GSP1KE/Upload-Assistant/commit/ea8cec3c4000747eb25ecf1c16fe93c79d8915f3
