### ISSUE TITLE
Dual-Audio in name

### ISSUE THREAD

**Issue by BradleyRL** [L4GSP1KE/Upload-Assistant#94]
Hi, the latest version adds Dual-Audio if it has an audio different than english in the torrent name is there a way to avoid this by using a parameter?, my tracker is an spanish tracker so everything has dual audio (en and es)

if not could you add one, please

**Comment by L4GSP1KE** [comment]
no arg, but LT will no longer have dual-audio in titles. Good enough?

https://github.com/L4GSP1KE/Upload-Assistant/commit/922005b718f9cd5511250df1526492c02e31ac39

**Comment by BradleyRL** [comment]
That's good enough, thanks
